---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bgd-subchart
  name: bgd-subchart
  namespace: bgd-subchart
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bgd-subchart
---
